---
#
# roles/dev/vars/main.yml
#

package_key:
  - 'https://packages.microsoft.com/keys/microsoft.asc'
  - 'https://download.sublimetext.com/sublimehq-pub.gpg'
package_repo:
  - 'deb https://download.sublimetext.com/ apt/stable/'
  - 'deb https://packages.microsoft.com/repos/vscode stable main'
  - 'ppa:ansible/ansible'
apt_packages: 
  - lightdm 
  - lightdm-gtk-greeter
  - xfwm4 
  - xfce4-panel 
  - xfce4-settings 
  - xfce4-session 
  - xfce4-terminal 
  - xfdesktop4 
  - xfce4-taskmanager 
  - tango-icon-theme
  - thunar
  - gvfs 
  - gvfs-backends 
  - policykit-1 
  - udisks2
  - firefox
  - xterm
  - git
  - nfs-common
  - cifs-utils
  - code
  - sublime-text
  - ansible
  - twine
aliases:
  - {name: 'ansible-vault', command: 'ansible-vault --vault-password-file ~/.ansibleCredential' }
  - {name: 'ansible-playbook', command: 'ansible-playbook  --vault-password-file ~/.ansibleCredential --inventory-file inventory/hosts.yml --private-key ~/.ssh/id_rsa-Ansible' }
  - {name: 'check-vault', command: 'for filename in $(find . -name "vault.yml"); do echo $filename $(head -n 1 $filename); done'}
ansible_credential: '{{ vault_ansible_credential }}'
git_name: 'Ian Day'
git_email: 'ian236day@gmail.com'
git_username: 'iandday'
git_repos: 
  - 'ssh://git@github.com/iandday/pyharmony.git'
  - 'ssh://git@github.com/iandday/ansiblePlaybooks.git'
  - 'ssh://git@github.com/iandday/hassConfig.git'

