---
#
# roles/gitlab/tasks/main.yml
#

- name: load common role variables
  include_vars: '{{ playbook_dir }}/roles/common/vars/{{ item }}.yml'
  with_items:
    - main
    - vault
  no_log: true
  
- name: load vault variables
  include_vars: vault.yml
  no_log: true

- name: check for required variables
  include_role: 
    name: common
    tasks_from: check_vars
  vars:
    req_vars: '{{ gitlab_required_variables }}'

- name: start gitlab build 
  include_role: 
    name: gitlab
    tasks_from: install_gitlab
