---
# roles/nginx/tasks/main.yml
    
- name: Install nginx
  become: yes
  become_user: root
  apt: 
    pkg: '{{ item }}'
    state: latest
  with_items:
    - nginx
    - nginx-extras

- name: disable default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent    
    
- name: restart nginx
  become: yes
  become_user: root
  service: 
    name: nginx
    state: restarted