---
#
# roles/nginx/tasks/main.yml
#

- name: Install nginx
  apt: 
    pkg: '{{ item }}'
    state: latest
  become: yes
  with_items:
    - nginx
    - nginx-extras

- name: disable default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent    
  become: yes
    
- name: restart nginx
  service: 
    name: nginx
    state: restarted
  become: yes