---
#
# roles/jellyfin/tasks/main.yml
#


# - name: check required variables
#   fail:
#     msg: "Variable '{{ item }}' is not defined"
#   when: item not in vars
#   loop: '{{ jellyfin_required_vars }}'

- name: load jellyfin install tasks
  include_tasks: jellyfin_install.yml