---
- name: Install Apache
  sudo: yes
  apt: 
    pkg: "{{ item }}"
    state: latest
  with_items: 
      - apache2
      - apache2-utils

- name: Install Apache Modules
  apache2_module: 
    state: present 
    name: "{{ item }}"
  notify: restart apache
  with_items: "{{ apache_modules }}"

- name: Start Apache at boot
  sudo: yes
  command: systemctl enable apache2
  
- name: Restart Apache
  service: 
    name: apache2 
    state: restarted
