- hosts: testHost
  vars:
    snapshot_details: "base snapshot after ansible play"
    snapshot_name: "Post Build"
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
  - name: deploy new VM from template
    include_role: 
      name: common
      tasks_from: deploy_vm_template
  - name: gather facts
    setup:
  - name: install python and perform base update
    include_role: 
      name: common
      tasks_from: initial_update
  roles:
  post_tasks:
  - name: reboot the server
    shell: sleep 2 && /sbin/shutdown -r now "system restart after Ansible play"
    async: 1
    poll: 0
  - name: wait for reboot
    wait_for_connection:
      delay: 1
      timeout: 300
  - name: set snapshot details
    set_fact:
      snapshot_details: "base snapshot after completion of ansible play"
      snapshot_name: "Post Build" 
  - name: take post play snapshot
    include_role:
      name: common
      tasks_from: snapshot