---
#configure base VM to host NextCloud server
- hosts: nextcloud-nc
  #vars:
    #ansible_python_interpreter: /usr/bin/python2.7
  vars_files:
    - roles/nextCloud/vars/main.yml
    - roles/nextCloud/vars/vault.yml
  become: true
  gather_facts: true
  tasks:
    - include: roles/nextCloud/tasks/backup.yml
