---
#
#  TvHeadend/Emby
#

- hosts: media
  gather_facts: false
  pre_tasks:
    - name: deploy new VM from template
      include_role: 
        name: common
        tasks_from: deploy_vm_template
    - name: gather facts
      setup:
    - name: join domain
      include_role: 
        name: common
        tasks_from: join_domain
    - name: take clean snapshot
      include_role:
        name: common
        tasks_from: snapshot
      vars:
        snapshot_details: "base snapshot after vm deployment from template"
        snapshot_name: "Pre Build" 
  roles:
   - tvheadend
    - emby 
  post_tasks:
    - name: restore tvheadend backup
      include_role:
        name: tvheadend
        tasks_from: restore_tvheadend
      vars:
        tvh_backup: '20180215/tvheadend-20180215.tar.gz'
    - name: restore emby backup
      include_role:
        name: emby
        tasks_from: restore_emby
      vars:
        emby_backup: '20180215/emby-20180215.tar.gz'
    - name: reboot
      include_role:
        name: common
        tasks_from: reboot
    - name: take post play snapshot
      include_role:
        name: common
        tasks_from: snapshot
      vars:  
        snapshot_details: "base snapshot after completion of ansible play"
        snapshot_name: "Post Build" 