---
# Home Assistant

- hosts: automation2
  gather_facts: false
  pre_tasks: 
    - name: deploy new VM from template
      include_role: 
        name: common
        tasks_from: deploy_vm_template
      vars:
        vcenter_vmtemplate: ubuntu1804Template
        vcenter_datastore: esxi2SSD
      when: inventory_hostname not in vm_check.virtual_machines
    - name: gather facts
      setup:
    # - name: join domain
    #   include_role: 
    #     name: common
    #     tasks_from: join_domain
  #   - name: take clean snapshot
  #     include_role:
  #       name: common
  #       tasks_from: snapshot
  #     vars:
  #       snapshot_details: "base snapshot after vm deployment from template"
  #       snapshot_name: "Pre Build" 
  #     when: inventory_hostname not in vm_check.virtual_machines
  # roles:
  #   - hass-18.04
  #   - cifs_server
  # post_tasks:
  #   - name: take post build snapshot
  #     include_role:
  #       name: common
  #       tasks_from: snapshot
  #     vars:
  #       snapshot_details: 'base snapshot after completion of ansible play'
  #       snapshot_name: 'Post Build' 
  #     when: inventory_hostname not in vm_check.virtual_machines