---
#configure base VM to host emby server
- hosts: emby
  vars:
    snapshot_details: "snapshot after install and initial start"
    hostname: "media"
    vm_name: "media"
    snapshot_name: "Base emby"
    ansible_python_interpreter: /usr/bin/python2.7
  vars_files:
    - roles/emby/vars/main.yml
    - roles/emby/vars/vault.yml
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python2.7 since Ubuntu 16.04 doesn't ship it
    raw: "sudo apt-get update -y && sudo apt-get install -y python2.7 aptitude"
  - name: change hostname
    include_role:
      name: common
      tasks_from: hostname 
  - name: gather facts
    setup:
  roles:
    - emby
  post_tasks:
  - name: take clean snapshot
    include_role:
      name: common
      tasks_from: snapshot