---
#
# roles/splunk/tasks/install_splunk.yml
#
    
- name: install packages
  include_role:
    name: common
  tasks_from: install_packages
  vars:
    packages: '{{ apt_packages }}'

- name: checking if splunk is installed
  stat: 
    path: /opt/splunk
  register: splunk_path

- name: download and install splunk package
  apt:
    deb: '{{ splunk_url }}'
    install_recommends: yes
  become: true
  when: splunk_path.stat.exists == false

- name: create splunk user
  user:
    name: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
  become: true

- name: mount data network share
  mount: 
    path: '{{ splunk_dir }}/var/lib/splunk' 
    src: '{{ network_path }}'
    fstype: nfs 
    state: mounted    
  become: true
    
- name: modify splunk directory permissions
  file:
    path: '{{ splunk_dir }}'
    owner: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
    recurse: yes
  become: true

- name: initial splunk start
  command: '{{ splunk_dir }}/bin/splunk start --accept-license'
  become: true
  become_user: '{{ splunk_user }}'
  when: splunk_path.stat.exists == false
  
- name: start splunk at boot
  command: '{{ splunk_dir }}/bin/splunk enable boot-start -user {{ splunk_user }}' 
  become: true
  when: splunk_path.stat.exists == false

- name: change splunk admin credentials
  shell: '{{ splunk_dir }}/bin/splunk edit user admin -password {{ splunk_admin_password }} -auth admin:changeme'
  become: true
  become_user: '{{ splunk_user }}'
  when: splunk_path.stat.exists == false

- name: transfer license file
  copy:
    src: '{{ license_filename }}' 
    dest: '{{ splunk_dir }}/{{ license_filename }}'
    owner: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
  become: true
  register: license_status

- name: register license 
  shell: '{{ splunk_dir }}/bin/splunk add licenses {{ splunk_dir }}/{{ license_filename }} -auth admin:{{ splunk_admin_password }}'
  become: true
  become_user: '{{ splunk_user }}'
  when: license_status is changed

- name: enable universal forwarder listener on tcp 9997
  shell: '{{ splunk_dir }}/bin/splunk enable listen 9997 -auth admin:{{ splunk_admin_password }}'
  become: true
  become_user: '{{ splunk_user }}'
  when: splunk_path.stat.exists == false

- name: mount splunk app share
  mount:
    src: '{{ splunk_app_share }}'
    name: /tmp/splunkapps
    state: mounted
    fstype: cifs
    opts: guest
  become: true

- name: identify apps to install
  find: 
    paths: /tmp/splunkapps
  register: splunk_apps

- name: debug
  debug:
    var: splunk_apps

- name: install apps
  unarchive:
    src: '{{ item.path }}'
    dest: '{{ splunk_dir }}/etc/apps/'
    remote_src: yes
  become: true
  become_user: '{{ splunk_user }}'
  with_items:
    - '{{ splunk_apps.files }}'
  
- name: clone apps from github
  git:
    repo: '{{ item }}'
    dest: '{{ splunk_dir }}/etc/apps/'
  become: true
  become_user: '{{ splunk_user }}'
  with_items:
    - '{{ splunk_app_repos }}'

- name: restart splunk
  shell: '{{ splunk_dir }}/bin/splunk restart'
  become: true
  become_user: '{{ splunk_user }}'

# Backup splunk??