---
#
# roles/splunk/tasks/install_splunk.yml
#
    
- name: install packages
  include_role:
    name: common
  tasks_from: install_packages
  vars:
    packages: '{{ apt_packages }}'
      
- name: download and install splunk package
  apt:
    deb: "{{ splunk_url }}"
    install_recommends: yes
  become: true
 
- name: create splunk user
  user:
    name: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
  become: true

- name: mount data network share
  mount: 
    path: '{{ splunk_dir }}/var/lib/splunk' 
    src: '{{ network_path }}'
    fstype: nfs 
    state: mounted    
  become: true
    
- name: modify splunk directory permissions
  file:
    path: '{{ splunk_dir }}'
    owner: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
    recurse: yes
  become: true

- name: initial splunk start
  command: '{{ splunk_dir }}/bin/splunk start --accept-license'
  become: true
  become_user: '{{ splunk_user }}'
  
- name: start splunk at boot
  command: '{{ splunk_dir }}/bin/splunk enable boot-start -user {{ splunk_user }}' 
  become: true

- name: change splunk admin credentials
  shell: '{{ splunk_dir }}/bin/splunk edit user admin -password {{ splunk_admin_password }} -auth admin:changeme'
  become: true
  become_user: '{{ splunk_user }}'

- name: transfer license file
  copy:
    src: '{{ license_filename }}' 
    dest: '{{ splunk_dir }}/{{ license_filename }}'
    owner: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
  become: true

- name: register license 
  shell: '{{ splunk_dir }}/bin/splunk add licenses {{ splunk_dir }}/{{ license_filename }} -auth admin:{{ splunk_admin_password }}'
  become: true
  become_user: '{{ splunk_user }}'

- name: enable universal forwarder listener on tcp 9997
  shell: '{{ splunk_dir }}/bin/splunk enable listen 9997 -auth admin:{{ splunk_admin_password }}'
  become: true
  become_user: '{{ splunk_user }}'

- name: mount splunk app share
  mount:
    src: '{{ splunk_app_share }}'
    name: /tmp/splunkapps
    state: mounted
    fstype: cifs
    opts: guest
  become: true

- name: identify apps to install
  find: 
    paths: /tmp/splunkapps
  register: splunk_apps

- name: install apps
  unarchive:
    src: '{{ item.path }}'
    dest: '{{ splunk_dir }}/etc/apps/'
    remote_src: yes
  with_items:
    - '{{ splunk_apps.files }}'
  become: true
  become_user: '{{ splunk_user }}'

- name: restart splunk
  shell: '{{ splunk_dir }}/bin/splunk restart'
  become: true
  become_user: '{{ splunk_user }}'

# Backup splunk??