---
#
# roles/splunk/tasks/main.yml
#


- name: check required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: '{{ splunk_required_vars }}'

- name: load splunk install tasks
  include_tasks: splunk_install.yml