---
#
# roles/jellyfin/defaults/main.yaml
#

jellyfin_required_vars:
  - jellyfin_movies_path
  - jellyfin_music_path
  - jellyfin_tv_path
  - jellyfin_dvr_path
  - jellyfin_movies_dest
  - jellyfin_music_dest
  - jellyfin_tv_dest
  - jellyfin_dvr_dest
jellyfin_apt_packages:
  - apt-transport-https
  - gnupg2
  - cifs-utils
jellyfin_gpg_key: 'https://repo.jellyfin.org/debian/jellyfin_team.gpg.key'
jellyfin_user: 110
jellyfin_group: 117
jellyfin_data_dir: '/var/lib/jellyfin'
jellyfin_config_dir: '/etc/jellyfin'
jellyfin_backup_dir: '/home/ansible/backup/jellyfin'