---
[localhost]
localhost ansible_connection=local

[splunk-ent]
splunk ansible_python_interpreter=/usr/bin/python3

[nextcloud]
ansibletest ansible_python_interpreter=/usr/bin/python3

[syslog-ng]
syslog ansible_python_interpreter=/usr/bin/python3