---
# [test]
# ansibleTest 

[splunk-ent]
splunk ansible_python_interpreter=/usr/bin/python3

[nextcloud-nc]
nextcloud ansible_python_interpreter=/usr/bin/python3

[syslog-ng]
syslog ansible_python_interpreter=/usr/bin/python3

[emby]
media ansible_python_interpreter=/usr/bin/python3

