---
all:
  children:
    splunk-ent:
      hosts:
        splunk: 
      vars:
        ansible_python_interpreter:/usr/bin/python3 
    nextcloud-nc:
      hosts:
          nextcloud:
            hostname: nextcloud 
            vm_name: "{{ hostname }}"
      vars:
          ansible_python_interpreter: /usr/bin/python
    syslog-ng:
      hosts:
        syslog:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    emby:
      hosts:
        media:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    utility:
      hosts:
        services:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    automation:
      hosts:
        hass:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    local:
      hosts:
        127.0.0.1:
      vars:
        ansible_connection: local      
    testHost:
      hosts:
          test28:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    reverse_proxy:
      hosts:
          revprox-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 


