---
all:
  children:
    development:
      hosts:
        dev-01: 
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        ad_user: '{{ ian_user }}'
        ad_user_password: '{{ ian_domain_password }}'
        ad_user_dn: '{{ ian_user_dn }}'
        vnc_vnc_user: '{{ ian_user }}'
        vnc_vnc_password: '{{ ian_vnc_password }}'
    splunk:
      hosts:
        splunk-01: 
      vars:
        ansible_python_interpreter: /usr/bin/python3
    nextcloud:
      hosts:
        nextcloud-01:
      vars:
        ansible_python_interpreter: /usr/bin/python
        vcenter_datastore: 'esxi2SSD'
        vcenter_memory_mb: 4096
        vcenter_template_disk_size: 40

    syslog:
      hosts:
        syslog-01:
          splunked_directories: 
            - { directory: '/var/log/syslog-ng/pfsense/*/*/*.log', sourcetype: 'pfsense_syslog', index: gw_pfsense, recursive: true  }
          syslog_config:
            - pfsense.conf
          syslog_service_password: '{{ vault_syslog_service_password }}'  
          syslog_service_username: 'svcSyslog'
          syslog_share: //FREENAS/syslog
          syslog_pfsense_receive_port: 5514
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    media:
      hosts:
        dvr-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        vcenter_lan_network: 
          - {"name": "DPortGroupLAN", "device_type": "vmxnet3", "type": "dhcp"} 
          - {"name": "DPortGroupCableTV", "device_type": "vmxnet3", "type": "dhcp"}
    utility:
      hosts:
        services:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    automation:
      hosts:
        ha-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    automation2:
      hosts:
        ha-02:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    reverse_proxy:
      hosts:
        revprox-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        log_group: 'www-data'
        splunked_directories: 
          - { directory: '/var/log/apache2/access.log', sourcetype: 'apache:access', index: apache, recursive: false }
          - { directory: '/var/log/apache2/error.log', sourcetype: 'apache:error', index: apache, recursive: false  } 
    gitlab:
      hosts:
        gitlab-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        vcenter_datastore: 'esxi2SSD'
        vcenter_memory_mb: 4096
        vcenter_template_disk_size: 40
    local:
      hosts:
        127.0.0.1:
      vars:
        ansible_connection: local
        ansible_python_interpreter: python
    testHost:
      hosts:
        test28:
      vars:
        ansible_python_interpreter: python3
