---
#
# inventory/hosts.yml
#

all:
  children: 
    docker:
      hosts:
        docker-01: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.9
        kvm_cores: 2
        kvm_memory: 5120
        kvm_net: '{"net0":"virtio=52:47:2C:C9:AD:1B,bridge=vmbr1"}'
        kvm_node: 'pve-01'
        docker_networks:
          - traefik_proxy
        docker_nfs_path: 10.168.1.3:/mnt/Main/dockernfs
        cifs_shares:
          share1:
            cifs_comments: 'HASS Config'
            cifs_path: '{{ docker_automation_hass_config }}'
          share2:
            cifs_comments: 'Appd Config'
            cifs_path: '{{ docker_automation_appdaemon_storage }}'
        cifs_user: docker
        cifs_password: '{{ vault_cifs_password_hass }}' 
        docker_automation_hass_ver: 0.105.4
        docker_automation_ha_url: 'https://hass.{{ all_ext_domain}}'
        docker_automation_appd_token: '{{ vault_docker_automation_appd_token }}'
        docker_utility_bitwarden_admin_token: '{{ vault_docker_utility_bitwarden_admin_token }}'
        docker_utility_bitwarden_duo_ikey: '{{ vault_docker_utility_bitwarden_duo_ikey }}'
        docker_utility_bitwarden_duo_skey: '{{ vault_docker_utility_bitwarden_duo_skey }}'
        docker_utility_bitwarden_duo_api: '{{ vault_docker_utility_bitwarden_duo_api }}'
        docker_utility_mail_server: 'smtp.gmail.com'
        docker_utility_mail_port: '465'
        docker_utility_mail_username: '{{ vault_docker_utility_mail_username }}'
        docker_utility_mail_password: '{{ vault_docker_utility_mail_password }}'
        docker_utility_mail_hostname: '{{ vault_docker_utility_mail_hostname }}'
        docker_utility_mail_networks: '{{ vault_docker_utility_mail_networks }}'

    nextcloud:
      hosts:
        nextcloud-03: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.5
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 2
        lxc_memory: 1024
        lxc_disk: 13
        lxc_storage: pve-data
        mysql_root_password: '{{ vault_nextcloud_mysql_root_password }}'
        mysql_user: nextclouduser
        mysql_password: '{{ vault_nextcloud_mysql_password }}'
        mysql_database: nextcloud
        server_name: cloud.ianday.me
        nextcloud_admin_password: '{{ vault_nextcloud_admin_password}}'
        nextcloud_service_username: svcNextcloud
        nextcloud_service_password: '{{ vault_nextcloud_ldap_bind_password }}'
        nextcloud_user_password: '{{ vault_nextcloud_user_password }}'
        nextcloud_user_salt: '{{ vault_nextcloud_user_salt }}'
        nextcloud_trusted_proxy: '{{ vault_nextcloud_trusted_proxy }}'
        docker_cache_partition: '/dev/sdb1'
    wiki:
      hosts:
        wiki-04: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.7
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 2
        lxc_memory: 1024
        lxc_disk: 13
        lxc_storage: pve-data
    media:
      hosts:
        media-01: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.15
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 2
        lxc_memory: 2048
        lxc_disk: 90
        lxc_storage: largeSSD
        jellyfin_movies_path: '//freenas/movies'
        jellyfin_music_path: '//freenas/music'
        jellyfin_tv_path: '//freenas/tv'
        jellyfin_movies_dest: '/mnt/movies'
        jellyfin_music_dest: '/mnt/music'
        jellyfin_tv_dest: '/mnt/tv'
        jellyfin_dvr_dest: '/mnt/dvr'
        jellyfin_service_username: svcEmby
        jellyfin_service_password: '{{ vault_jellyfin_service_password }}'
    omada:
      hosts:
        omada-01: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.28
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 2
        lxc_memory: 2048
        lxc_disk: 20
        lxc_storage: largeSSD
    music_streamer:
      hosts:
        mopidy-01: 
          ansible_host: 10.168.1.29
          lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
          lxc_node: 'pve-01'
          lxc_cores: 2
          lxc_memory: 1024
          lxc_disk: 12
          lxc_storage: largeSSD
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'

        mopidy_apt_list: 'deb https://apt.mopidy.com/ buster main contrib non-free'
        snapcast_sources:
          - 'source = pipe:///tmp/snapfifo?name=mopidy'
          - 'source = spotify:///librespot?name=spotify&devicename=Snapcast&bitrate=320'
        mopidy_jellyfin_host: '{{ vault_mopidy_jellyfin_host }}'
        mopidy_jellyfin_username: '{{ vault_mopidy_jellyfin_username }}'
        mopidy_jellyfin_password: '{[ vault_mopidy_jellyfin_password }}'
        mopidy_pandora_partner_encryption_key: '{{ vault_mopidy_pandora_partner_encryption_key }}'
        mopidy_pandora_partner_decryption_key: '{{ vault_mopidy_pandora_partner_decryption_key }}'
        mopidy_pandora_partner_password: '{{ vault_mopidy_pandora_partner_password }}'
        mopidy_pandora_username: '{{ vault_mopidy_pandora_username }}'
        mopidy_pandora_password: '{{ vault_mopidy_pandora_password }}'
    syslog:
      hosts:
        syslog-01:
          ansible_host: 10.168.1.41
          lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
          lxc_node: 'pve-01'
          lxc_cores: 1
          lxc_memory: 1024
          lxc_disk: 8
          lxc_storage: pve-data
          syslog_ng_log_path: '{{ vault_syslog_ng_log_path }}'
          syslog_ng_pfsense_receive_port: 654
          syslog_ng_omada_receive_port: 653
          syslog_ng_config:
            - 'pfsense.conf'
            - 'omada.conf'
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        reboot_handler: reboot LXC
        syslog_ng_log_service_username: '{{ vault_syslog_ng_log_service_username }}'
        syslog_ng_log_service_password: '{{ vault_syslog_ng_log_service_password }}'

  vars:
    reboot_handler: reboot