---
#
# inventory/hosts.yml
#

all:
  children: 
    docker:
      hosts:
        docker-01: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.9
        kvm_cores: 2
        kvm_memory: 5120
        kvm_net: '{"net0":"virtio=52:47:2C:C9:AD:1B,bridge=vmbr1"}'
        kvm_node: 'pve-01'
        docker_networks:
          - traefik_proxy
        docker_nfs_path: 10.168.1.3:/mnt/Main/dockernfs
        cifs_shares:
          share1:
            cifs_comments: 'HASS Config'
            cifs_path: '{{ docker_automation_hass_config }}'
          share2:
            cifs_comments: 'Appd Config'
            cifs_path: '{{ docker_automation_appdaemon_storage }}'
        cifs_user: docker
        cifs_password: '{{ vault_cifs_password_hass }}' 
        docker_automation_hass_ver: 0.105.4
        docker_automation_ha_url: 'https://hass.{{ all_ext_domain}}'
        docker_automation_appd_token: '{{ vault_docker_automation_appd_token }}'
    nextcloud:
      hosts:
        nextcloud-02: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.5
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 2
        lxc_memory: 1024
        lxc_disk: 13
        lxc_storage: pve-data
        mysql_root_password: '{{ vault_nextcloud_mysql_root_password }}'
        mysql_user: nextclouduser
        mysql_password: '{{ vault_nextcloud_mysql_password }}'
        mysql_database: nextcloud
        server_name: cloud.ianday.me
        nextcloud_admin_password: '{{ vault_nextcloud_admin_password}}'
        nextcloud_service_username: svcNextcloud
        nextcloud_service_password: '{{ vault_nextcloud_ldap_bind_password }}'
        nextcloud_user_password: '{{ vault_nextcloud_user_password }}'
        nextcloud_user_salt: '{{ vault_nextcloud_user_salt }}'
        nextcloud_trusted_proxy: '{{ vault_nextcloud_trusted_proxy }}'
    wiki:
      hosts:
        wiki-04: 
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.7
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 2
        lxc_memory: 1024
        lxc_disk: 13
        lxc_storage: pve-data
    syslog:
      hosts:
        syslog-02:
      vars:
        ansible_python_interpreter: '{{ all_ansible_python_interpreter }}'
        ansible_host: 10.168.1.69
        lxc_net: '{"net0":"name=eth0,gw={{ all_gateway }},ip={{ ansible_host}}/24,bridge=vmbr1"}'
        lxc_node: 'pve-01'
        lxc_cores: 1
        lxc_memory: 1024
        lxc_disk: 13
        lxc_storage: pve-data
        syslog_config:
          - pfsense.conf
