---
all:
  children:
    development:
      hosts:
        dev-01: 
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        ad_user: '{{ ian_user }}'
        ad_user_password: '{{ ian_domain_password }}'
        ad_user_dn: '{{ ian_user_dn }}'
        vnc_vnc_user: '{{ ian_user }}'
        vnc_vnc_password: '{{ ian_vnc_password }}'
    splunk:
      hosts:
        splunk-01: 
      vars:
        ansible_python_interpreter: /usr/bin/python3
    nextcloud-nc:
      hosts:
          nextcloud:
            hostname: nextcloud 
            vm_name: "{{ hostname }}"
      vars:
          ansible_python_interpreter: /usr/bin/python
    syslog:
      hosts:
        syslog-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        log_group: 'syslog'
        splunked_directories: 
          - { directory: '/var/log/syslog-ng/pfsense/*/*/*.log', sourcetype: 'pfsense_syslog', index: gw_pfsense, recursive: true  }
    media:
      hosts:
        dvr-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        vcenter_lan_network: 
          - {"name": "DPortGroupLAN", "device_type": "vmxnet3", "type": "dhcp"} 
          - {"name": "DPortGroupCableTV", "device_type": "vmxnet3", "type": "dhcp"}
    utility:
      hosts:
        services:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    automation:
      hosts:
        hass:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
    reverse_proxy:
      hosts:
        revprox-01:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        log_group: 'www-data'
        splunked_directories: 
          - { directory: '/var/log/apache2/access.log', sourcetype: 'apache:access', index: apache, recursive: false }
          - { directory: '/var/log/apache2/error.log', sourcetype: 'apache:error', index: apache, recursive: false  } 
    local:
      hosts:
        127.0.0.1:
      vars:
        ansible_connection: local      
    testHost:
      hosts:
        test28:
      vars:
        ansible_python_interpreter: /usr/bin/python3 
        vcenter_lan_network: 
          - {"name": "DPortGroupLAN", "device_type": "vmxnet3", "type": "dhcp"} 
          - {"name": "DPortGroupCableTV", "device_type": "vmxnet3", "type": "dhcp"}

