---
# roles/duoProxy/tasks/main.yml
- include_vars: vault.yml
- name: update apt cache and install required packages
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"
  
- name: download duo auth proxy source
  get_url:
    url: "{{ tar_url }}"
    dest: /opt/
  register: downloaded

- name: unpack duo proxy source
  unarchive:
    remote_src: True
    src: '{{ downloaded.dest }}'
    dest: '/opt/'

    
- name: set python variable
  raw: 'export PYTHON=$(which python)'

- name: compile code
  make:
    chdir: '{{ downloaded.dest[:-4] }}'

- name: install
  command: './install --install-dir={{ install_dir }} --create-init-script=yes --service-user={{ service_user }}'
  args:
    chdir: '{{ downloaded.dest[:-4] }}/duoauthproxy-build'
  become: yes
  become_user: root

- name: backup default config 
  command: mv /opt/duoauthproxy/conf/authproxy.cfg /opt/duoauthproxy/conf/authproxy.cfg.bak

- name: copy config
  template:
    src: roles/duoProxy/templates/authproxy.cfg.j2
    dest: /opt/duoauthproxy/conf/authproxy.cfg

- name: restart service
  service:
    name: duoauthproxy
    state: restarted
