---
#
# roles/apache_reverse_proxy/handlers/main.yml
#

- name: restart apache
  service:
    name: apache2
    state: restarted
  become: true
- name: restart incron
  service:
    name: incron
    state: restarted
  become: true