---
syslog_key: http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04/Release.key
syslog_repo: "deb http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04 ./"
apt_packages: 
    - syslog-ng-core
    - nfs-common
syslog_receive_port: 514
destination_ip: 10.168.1.10
destination_port: 5000
log_dir: /var/log/syslog-ng/
nfs_server: 10.168.1.3
nfs_path: /mnt/Main/syslog