---

- name: copy deb file
  copy:
    src: '{{ role_path }}/files/{{ deb_file }}'
    dest: '/tmp/{{ deb_file }}'
  become: true
  become_user: root

- name: installdeb
  apt:
    deb: '/tmp/{{ deb_file }}'
  become: true
  become_user: root

- name: create splunk user
  user:
    name: '{{ splunk_user }}'
    system: yes
    groups: '{{ splunk_group }},{{ log_group }}'
  become: true
  become_user: root

- name: change ownership of splunk directory
  file:
    path: '{{ splunk_path }}'
    owner: '{{ splunk_user }}'
    group: '{{ splunk_group }}'
    state: directory
    recurse: yes  
  become: true
  become_user: root

- name: change permissions for directory to be monitored
  file:
    path: '{{ item.directory }}'
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - '{{ splunked_directories }}'
  become: true
  become_user: root

- name: start splunk
  shell: '{{ splunk_path }}/bin/splunk start --accept-license'
  become: true
  become_user: '{{ splunk_user }}'

- name: enable boot-start
  shell: '{{ splunk_path }}/bin/splunk enable boot-start -user {{ splunk_user }}'
  become: true
  become_user: root

- name: change forwarder admin credentials
  shell: '{{ splunk_path }}/bin/splunk edit user admin -password {{ forwarder_password }} -auth admin:changeme'
  become: true
  become_user: '{{ splunk_user }}'

- name: configure forward-server
#  shell: /opt/splunkforwarder/bin/splunk add forward-server '{{ server_host }}':'{{ server_port }}' -auth admin:'{{ forwarder_password }}'
  blockinfile:
    path: /opt/splunkforwarder/etc/system/local/outputs.conf
    create: yes
    block: |
      [tcpout]
      defaultGroup = default-autolb-group

      [tcpout:default-autolb-group]
      server = {{ server_host }}:{{ server_port }}

      [tcpout-server://{{ server_host }}:{{ server_port }}]
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  become: true
  become_user: '{{ splunk_user }}'

- name: add directories to monitor
  blockinfile:
    path: '{{ splunk_path }}/etc/system/local/inputs.conf'
    create: yes
    block: |
      [monitor://{{ item.directory }}] 
      sourcetype={{ item.sourcetype }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK Monitoring directory: {{item.directory}}"
  become: true
  become_user: '{{ splunk_user }}'
  with_items: "{{ splunked_directories }}"

- name: restart splunkd
  shell: '{{ splunk_path }}/bin/splunk restart'
  become: true
  become_user: '{{ splunk_user }}'

