---
#
# roles/hass/handlers/main.yml
#

  - name: restart hass
    service:
      name: '{{ hass_service }}'
      state: restarted
    notify: restart appdaemon
    become: true

  - name: restart appdaemon
    service:
      name: '{{ hass_appdameon_service }}'
      state: restarted
    become: true