---
#configure base VM to host emby server
- hosts: emby
  vars:
    snapshot_details: "snapshot after install and initial start"
    hostname: "media"
    vm_name: "media"
    snapshot_name: "Base emby install"

  become: true
  gather_facts: false
  pre_tasks:
  - name: initial update
    include_role: 
      name: common
      tasks_from: initial_update
  - name: change hostname
    include_role:
      name: common
      tasks_from: hostname 
  - name: gather facts
    setup:
  roles:
    - emby
  post_tasks:
  - name: take clean snapshot
    include_role:
      name: common
      tasks_from: snapshot