---
#configure base VM to host NextCloud server
- hosts: testHost
  vars:
    snapshot_details: "snapshot after install and initial start"
    hostname: "test1"
    vm_name: "test1"
    snapshot_name: "Base nextcloud"
    ansible_python_interpreter: /usr/bin/python2.7
  vars_files:
    - roles/nextcloud_install/vars/main.yml
    - roles/nextcloud_install/vars/vault.yml
  become: true
  become_user: root
  gather_facts: false
  pre_tasks:
  - name: Install python2.7 since Ubuntu 16.04 doesn't ship it
    raw: "sudo apt-get update -y && sudo apt-get install -y python2.7 aptitude"
  - name: change hostname
    include_role:
      name: common
      tasks_from: hostname 
  - name: gather facts
    setup:
  roles:
    - nginx
    - mysql   
    - nextcloud_install
  post_tasks:
  - name: take clean snapshot
    include_role:
      name: common
      tasks_from: snapshot
  - name: reboot the server
    command: /sbin/reboot