- hosts: testHost
  vars:
    snapshot_details: "base snapshot after ansible play"
    snapshot_name: "Post Build"
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
  - name: deploy new VM from template
    include_role: 
      name: common
      tasks_from: deploy_vm_template
  - name: gather facts
    setup:
  - name: install python and perform base update
    include_role: 
      name: common
      tasks_from: initial_update
  - name: take clean snapshot
    include_role:
      name: common
      tasks_from: snapshot
  roles:
    - apache_reverse_proxy
    - lets_encrypt
  post_tasks:
  - name: Restart Apache
    service: 
      name: apache2 
      state: restarted
  - name: take clean snapshot
    include_role:
      name: common
      tasks_from: snapshot
  - name: reboot the server
    shell: sleep 2 && /sbin/shutdown -r now "system restart after Ansible play"
    async: 1
    poll: 0
  - name: wait for reboot
    local_action:
      module: wait_for_connection
      delay: 1
      timeout: 300