---
# Duo authentication proxy and Unfi controller

- hosts: utility
  become: yes
  become_user: root
  vars:
    hostname: 'services'
    vm_name: 'services'
    snapshot_name: 'base'
    snapshot_details: 'Duo auth proxy and unifi controller'
  pre_tasks:    
  - name: intial
    include_role:
      name: common
      tasks_from: initial_update
  - name: change hostname
    include_role:
      name: common
      tasks_from: hostname 
  - name: gather facts
    setup:
  roles:
    - unifi
    - duoProxy
  post_tasks:
    - name: take clean snapshot
      include_role:
        name: common
        tasks_from: snapshot