---
#configure base VM to host syslog-ng
- hosts: syslog-ng
  vars:
    snapshot_details: "snapshot after install and initial start"
    hostname: "syslog"
    vm_name: "syslog"
    snapshot_name: "Clean Syslog with UTM config"
  become: true
  gather_facts: false
  
  pre_tasks:
  - name: Install python2.7 since Ubuntu 16.04 doesn't ship it
    raw: "sudo apt-get update -y && sudo apt-get install -y python2.7 aptitude"
  - name: gather facts
    setup:
  - name: change hostname
    include_role:
      name: common
      tasks_from: hostname
  
  roles:
    - syslog
  
  post_tasks:
  - name: take clean snapshot
    include_role:
      name: common
      tasks_from: snapshot