---
#
# roles/apache_reverse_proxy/tasks/main.yml
#

- name: load vault variables
  include_vars: vault.yml
  no_log: true

- name: check required variables
  import_tasks: check_vars.yml

- name: load apache reverse proxy install tasks
  import_tasks: apache_reverse_proxy_install.yml
