---
#
# roles/apache_reverse_proxy/tasks/main.yml
#

- name: load vault variables
  include_vars: vault.yml
  no_log: true

- name: check for required variables
  include_role: 
    name: common
    tasks_from: check_vars
  vars:
    req_vars: '{{ apache_required_variables }}'

- name: load apache reverse proxy install tasks
  import_tasks: apache_reverse_proxy_install.yml
