---
#
# roles/splunk/defaults/main.yaml
#

splunk_required_vars:
  - splunk_admin_password
splunk_apt_packages:
  - nfs-common
  - cifs-utils
  - git
splunk_url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.2.0&product=splunk&filename=splunk-8.2.0-e053ef3c985f-linux-2.6-amd64.deb&wget=true'
splunk_user: splunk
splunk_group: splunk
splunk_dir: '/opt/splunk'


