---
#
# roles/mysql/tasks/main.yml 
#

- name: Specify MySQL root password before installing to disable auth_socket
  debconf: 
    name: mysql-server
    question: "{{ item }}"
    value: "{{ mysql_root_password | quote }}" 
    vtype: password
  become: true
  with_items: 
    - mysql-server/root_password
    - mysql-server/root_password_again
    
- name: Install MySQL Packages
  become: true
  apt: 
    pkg: "{{ item }}" 
    state: latest
    force: yes
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb
    - libmysqlclient-dev

- name: Start mariadb
  service: 
    name: mysql
    state: started 
    enabled: yes

- name: copy mysql credential file
  become: true
  template:
    src: roles/mysql/templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Update root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}" 
    priv: "*.*:ALL,GRANT"
  with_items: "{{ mysql_hosts }}"
  become: true

- name: check and remove anonymous users
  mysql_user: 
    name: '' 
    host: "{{ item }}" 
    state: absent
  with_items: "{{ mysql_hosts }}"    
  become: true
        
- name: Create databases
  mysql_db: 
    name: "{{ mysql_database }}"
    state: present 
    login_user: root 
    login_password: "{{ mysql_root_password }}"
  become: true
    
- name: create users
  mysql_user: 
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}" 
    priv: "{{ mysql_database }}.*:ALL" 
    state: present 
    login_user: root 
    login_password: "{{ mysql_root_password }}"
  become: true
