---
#
# roles/splunk_forwarder/vars/main.yml
#

uf_deb_file:  splunkforwarder-7.0.1-2b5b15c4ee89-linux-2.6-amd64.deb
uf_forwarder_password: '{{ vault_forwarder_password }}'
uf_server_host: splunk.daynet.ianday.me
uf_server_port: 9997
