---
#roles/unifi/tasks/main.yml

- name: add unifi apt key
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80 
    id: C0A52C50
  become: yes
  become_user: root
  
- name: add unifi source
  lineinfile:
    dest: /etc/apt/sources.list.d/ubnt.list
    line: '{{ unifi_repo }}'
    create: yes
  become: yes
  become_user: root
  
- name: install unifi package
  apt:
    name: unifi
    update_cache: yes
    state: latest
  become: yes
  become_user: root

- name: start unifi and mongodb at boot 
  service: 
    name: '{{ item }}'
    enabled: yes 
    state: started
  with_items:
    - unifi
    - mongodb