---
# roles/cifsServer/tasks/main.yml

- name: check required variables
  fail: 
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - cifs_user
    - cifs_password
    - cifs_path
    - cifs_comments
    
- name: install packages
  become: yes
  become_user: root
  apt: 
    name: '{{ item }}'
    state: installed
  with_items:
    - '{{ required_cifs_pkgs }}'


- name: template config file
  become: yes
  become_user: root
  template: 
    src: smb.conf.j2 
    dest: /etc/samba/smb.conf

- name: Create password for samba users
  become: yes
  become_user: root
  shell: '(echo  {{ cifs_password }}; echo {{ cifs_password }}) | smbpasswd -s -a {{ cifs_user }}'

- name: start samba at boot.
  become: yes
  become_user: root
  service:
    name: smbd
    state: started 
    enabled: yes