---
#
# roles/syslog/tasks/main.yml
#

- name: check required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: '{{ syslog_required_vars }}'

- name: load install tasks
  include_tasks: syslog_install.yml


