---
#
# roles/cifs_server/tasks/main.yml
#

- name: load common role variables
  include_vars: '{{ playbook_dir }}/roles/common/vars/{{ item }}.yml'
  with_items:
    - main
    - vault
  no_log: true

- name: check for required variables
  include_role: 
    name: common
    tasks_from: check_vars
  vars:
    req_vars: '{{ cifs_server_required_variables }}'

- name: wait for response
  wait_for_connection:
    delay: 1
    timeout: 300
  delegate_to: localhost

- name: start main play
  include_tasks: install_cifs_server.yml