---
#
# roles/vnc/tasks/install_vnc.yml
#

- name: install packages
  include_role:
    name: common
    tasks_from: install_packages
  vars:
    packages: '{{ vnc_apt_packages }}'

- name: download tigervnc deb
  apt:
    deb: '{{ vnc_tigervnc_deb }}'
  become: true

- name: get user details
  getent:
    database: passwd
    key: '{{ vnc_vnc_user }}'

- name: set user facts
  set_fact:
    uid: '{{ getent_passwd[vnc_vnc_user][1] }}'
    gid:  '{{ getent_passwd[vnc_vnc_user][2] }}'
    home: '{{ getent_passwd[vnc_vnc_user][4] }}'

- name: create .vnc directory
  file:
    path: '/home/{{ vnc_vnc_user }}/.vnc'
    owner: '{{ uid }}'
    group: '{{ gid }}'
    mode: '0755'
    state: 'directory'
  become: yes

- name: set vnc password
  shell: 'echo {{ vnc_vnc_password }} | vncpasswd -f > /home/{{ vnc_vnc_user }}/.vnc/passwd'
  args:
    executable: /bin/bash
    creates: '/home/{{ vnc_vnc_user }}/.vnc/passwd'
  notify: restart vnc
  become: true

- name: secure vnc password file
  file:
    path: '/home/{{ vnc_vnc_user }}/.vnc/passwd'
    owner: '{{ uid }}'
    group: '{{ gid }}'
    mode: 0600
  become: true

- name: copy xstartup file
  template:
    src: 'xstartup.j2'
    dest: '/home/{{ vnc_vnc_user }}/.vnc/xstartup'
    mode: 0755
  notify: restart vnc
  become: true

- name: copy vnc server config
  template:
    src: vncservers.conf.j2
    dest: /etc/vncservers.conf
    owner: root
    group: root
    mode: '0755'
  notify: restart vnc
  become: true

- name: copy system.d file
  template:
    src: vncserver.j2
    dest: /etc/init.d/vncserver
    owner: root
    group: root
    mode: '0755'
  notify: restart vnc
  become: true

- name: start vncserver at boot
  service:
    name: vncserver
    enabled: yes
  notify: restart vnc
  become: true
  