---
#
# roles/vnc/tasks/install_vnc.yml
#

- name: install packages
  include_role:
    name: common
    tasks_from: install_packages
  vars:
    packages: '{{ apt_packages }}'

- name: Set vnc password
  shell: 'x11vnc -storepasswd {{ vnc_password }} /etc/x11vnc.pass'
  no_log: true
  become: true

- name: install vnc service
  template:
    src: 'x11vnc.service.j2'
    dest: '/etc/systemd/system/x11vnc.service'
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rx,o=rx'
  become: true

- name: start vnc at boot
  service:
    name: x11vnc.service
    enabled: yes
    state: started
  become: true

