---
# roles/hass/tasks/update.yml

- include_vars: vault.yml
  no_log: true 

- name: determine installed HASS version
  command: bin/hass --version
  args:
    chdir: "{{ install_dir }}/bin"
  register: hass_installed

- name: determine current HASS version  

# - name: stop HASS
  # become: true
  # become_user: root
  # service:
    # name: home-assistant@homeassistant
    # state: stopped
    
# - name: take preupdate snapshot
  # include_role:
    # name: common
    # tasks_from: snapshot
    
# - name: mount backup directory
  # include_role:
    # name: common
    # tasks_from: mount_backup
  # vars:
    # backup_path: "{{ backup_root_path}}/hass/"
    # backup_uid: '{{ hass_user}}'
    # backup_gid: '{{ hass_user}}'
    
# - name: backup config
  # become: true
  # become_user: '{{ hass_user}}'
  # synchronize:
    # dest: '{{ backup_dir }}'
    # src: '{{ config_dir }}'
  # delegate_to: "{{ inventory_hostname }}" 

# - name: apt update/upgrade
  # include_role:
    # name: common
    # tasks_from: initial_update
  
# - name: update hass
  # become: yes
  # become_user: '{{ hass_user }}'
  # pip: 
    # name: homeassistant
    # virtualenv: '{{ install_dir }}'  
    # state: latest

# - name: start HASS
  # become: true
  # become_user: root
  # service:
    # name: home-assistant@homeassistant
    # state: started