---
#
# roles/common/tasks/add_ntp.yml
#

- name: Install ntp package
  apt:
    name: ntp
    state: present
  become: true
  become_user: root

- name: Configure ntp service
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: yes
  become: true
  become_user: root

- name: start ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  become: true
  become_user: root