---
#
# roles/common/deploy_vm_tamplate.yml
#

- name: import vCenter credentials
  include_vars: '{{ item }}'
  with_items:
    - vault.yml
    - main.yml
  no_log: true

- name: check if vm exists
  vmware_vm_facts:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}'  
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_validate }}'
  delegate_to: localhost
  register: vm_check
  changed_when: false

- name: Create a VM from a template
  vmware_guest:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}'  
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_validate }}'
    folder: '{{ vcenter_folder }}'
    name: '{{ inventory_hostname }}'
    state: poweredon
    template: '{{ vcenter_vmtemplate }}'
    hardware:
      memory_mb: '{{ vcenter_memory_mb }}'
    disk:
    - size_gb: '{{ vcenter_template_disk_size }}'
      type: thin
      datastore: '{{ vcenter_datastore }}'
    datacenter: '{{ vcenter_datacenter }}'
    esxi_hostname: '{{ vcenter_esxi_hostname }}'
    networks: '{{ vcenter_lan_network }}'

  delegate_to: localhost
  register: deploy
  when: inventory_hostname not in vm_check.virtual_machines

- name: wait for vmtools to initialize
  pause:
    seconds: 30
  when: inventory_hostname not in vm_check.virtual_machines

- name: Change hostname and reboot
  vmware_vm_shell:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}' 
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_validate }}'
    folder: '{{ vcenter_folder }}'
    datacenter: '{{ vcenter_datacenter }}'
    vm_id: '{{ deploy.instance.hw_product_uuid }}'
    vm_id_type: uuid
    vm_username: '{{ vm_user }}'
    vm_password: '{{ vm_pass }}'
    vm_shell: '/usr/bin/sudo'
    vm_shell_args: '{{ item }}'
    vm_shell_cwd: '/tmp'
  with_items: 
    - "sed -i 's/ansible/{{ inventory_hostname }}/g' /etc/hosts"
    - "sed -i 's/ansible/{{ inventory_hostname }}/g' /etc/hostname"
    - "sed -i 's/preserve_hostname: false/preserve_hostname: true/g' /etc/cloud/cloud.cfg"
    - "apt-get update"
    - "apt-get install -y {{ common_packages }}"
    - "/sbin/reboot"
  delegate_to: localhost
  when: inventory_hostname not in vm_check.virtual_machines

- name: pause
  pause: 
    prompt: check IP address in vCenter
  when: inventory_hostname not in vm_check.virtual_machines

- name: wait for reboot
  wait_for_connection:
    delay: 15
    timeout: 300
  when: inventory_hostname not in vm_check.virtual_machines
  
- name: gather facts
  setup:

- name: Configure ntp service
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: yes
  become: true

- name: start ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  become: true
