---
#
# roles/common/deploy_vm_tamplate.yml
#

- name: import vCenter credentials
  include_vars:
    file: '{{ item }}'
  with_items:
    - main.yml
    - vault.yml
  no_log: true

- name: Create a VM from a template
  vmware_guest:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}'  
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_validate }}'
    folder: '{{ vcenter_folder }}'
    name: '{{ inventory_hostname }}'
    state: poweredon
    template: '{{ vcenter_vmtemplate }}'
    datacenter: '{{ vcenter_datacenter }}'
    networks:
    - name: '{{ vcenter_lan_network }}'
  delegate_to: localhost
  register: deploy

- name: Change hostname and reboot
  vmware_vm_shell:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}' 
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_validate }}'
    folder: '{{ vcenter_folder }}'
    datacenter: '{{ vcenter_datacenter }}'
    vm_id: '{{ deploy.instance.hw_product_uuid }}'
    vm_id_type: uuid
    vm_username: '{{ vm_user }}'
    vm_password: '{{ vm_pass }}'
    vm_shell: '/usr/bin/sudo'
    vm_shell_args: '{{ item }}'
    vm_shell_cwd: '/tmp'
  with_items: 
    - "sed -i 's/ubuntuTemplate/{{ inventory_hostname }}/g' /etc/hosts"
    - "sed -i 's/ubuntuTemplate/{{ inventory_hostname }}/g' /etc/hostname"
    - "apt-get update"
    - "apt-get install -y {{ common_packages }}"
    - "/sbin/reboot"
  delegate_to: localhost

- name: wait for reboot
  wait_for_connection:
    delay: 1
    timeout: 300

- name: initial package upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
  become_user: root
  become: true