---
#
# roles/common/tasks/install_dev.yml
#

- name: upgrade apt packages manually 
  sudo: true
  shell: 'apt-get update'
  warn: no
  become: true

- name: install packages
  apt: 
    name: '{{ item }}' 
    state: present
    update_cache: no
  with_items: '{{ packages }}'
  become: true
