---
#
# roles/common/tasks/install_packages.yml
#

- name: upgrade apt packages manually 
  shell: 'apt-get update'
  args:
    warn: no
  become: true

- name: install packages
  apt: 
    name: '{{ item }}' 
    state: present
    update_cache: no
  with_items: 
    - '{{ packages }}'
  become: true
