---
#
# roles/common/tasks/mount_backup.yml
#

- name: unmount backup share if mounted
  mount: 
    state: unmounted 
    path: '/mnt/backup_{{ path }}'
  become: true

- name: mount root backup share
  mount: 
    state: mounted 
    fstype: cifs
    src: '//freenas/backup/'
    path: '/mnt/backup_{{ path }}'
    opts: 'domain={{ domain.split(".")[0] }},username={{ username }},password={{ password }},uid={{ uid }},gid={{ gid }}'
  no_log: true
  become: true

- name: create backup directory if not found
  file:
    path: '/mnt/backup_{{ path }}/{{ path }}'
    state: directory
  become: true

- name: unmount root backup share
  mount: 
    state: unmounted 
    path: '/mnt/backup_{{ path }}'
  become: true

- name: mount backup share
  mount: 
    state: mounted 
    fstype: cifs
    src: '//freenas/backup/{{ path}}'
    path: '/mnt/backup_{{ path }}'
    opts: 'domain={{ domain.split(".")[0] }},username={{ username }},password={{ password }},uid={{ uid }},gid={{ gid }}'
  no_log: true
  become: true