---
#
# roles/common/tasks/mount_home.yml
#

- name: load variables
  include_vars: '{{ item }}'
  with_items:
    - vault.yml
    - main.yml
  no_log: true

- name: get user details
  getent:
    database: passwd
    key: '{{ ad_user }}'

- name: create credential file
  template:
    src: '.smbcredential.j2'
    dest: '/home/{{ ad_user }}/.smbcredential'
    mode: 0600
    owner: '{{ getent_passwd[ad_user][1] }}'
    group: '{{ getent_passwd[ad_user][2] }}'
  become: true

- name: get network home path
  shell: "ldapsearch -x -h {{ domain_controller }} -D {{ domain_join_user }}@{{ workgroup }} -w {{ domain_join_password }} -b '{{ ad_user_dn }}' homeDirectory | grep homeDirectory: | awk -F ' ' '{print $2}'"
  no_log: true
  register: network_home_path

- name: mount home directory
  mount: 
    src: '{{ network_home_path.stdout }}' 
    path: '{{ network_home_mount }}'
    state: 'mounted' 
    fstype: 'cifs' 
    opts: 'credentials=/home/{{ ad_user }}/.smbcredential,uid={{ getent_passwd[ad_user][1] }},gid={{ getent_passwd[ad_user][2] }},iocharset=utf8,file_mode=0770,dir_mode=0770'
  become: true
