---
#
# roles/common/tasks/mount_home.yml
#

- name: load vault variables
  include_vars: vault.yml
  no_log: true

- name: get user details
  getent:
    database: passwd
    key: '{{ cifs_user }}'

- name: get network home path
  shell: "ldapsearch -x -h {{ domain_controller }} -D {{ domain_join_user }}@{{ workgroup }} -w {{ domain_join_password }} -b '{{ cifs_dn }}' homeDirectory | grep homeDirectory: | awk -F ' ' '{print $2}'"
  no_log: true
  register: network_home_path

- name: mount home directory
  mount: 
    src: '{{ network_home_path.stdout }}' 
    path: '{{ getent_passwd[cifs_user][4]}}'
    state: 'mounted' 
    fstype: 'cifs' 
    opts: 'domain={{ workgroup|upper }},username={{ cifs_user }},password={{ cifs_password }},uid={{ getent_passwd[cifs_user][1] }},gid={{ getent_passwd[cifs_user][2] }},file_mode=0777,dir_mode=0777'
  #no_log: true
  become: true
  become_user: root