---
#
# roles/common/tasks/mount_home.yml
#

- name: load variables
  include_vars: '{{ item }}'
  with_items:
    - vault.yml
    - main.yml
  no_log: true

- name: get user details
  getent:
    database: passwd
    key: '{{ ad_user }}'

- name: get network home path
  shell: "ldapsearch -x -h {{ domain_controller }} -D {{ domain_join_user }}@{{ workgroup }} -w {{ domain_join_password }} -b '{{ ad_user_dn }}' homeDirectory | grep homeDirectory: | awk -F ' ' '{print $2}'"
  no_log: true
  register: network_home_path

- name: mount home directory
  mount: 
    src: '{{ network_home_path.stdout }}' 
    path: '{{ network_home_mount }}'
    state: 'mounted' 
    fstype: 'cifs' 
    opts: 'domain={{ workgroup|upper }},username={{ ad_user }},password={{ ad_user_password }},uid={{ getent_passwd[ad_user][1] }},gid={{ getent_passwd[ad_user][2] }},file_mode=0777,dir_mode=0777'
  become: true
