---
#
# roles/common/tasks/mount_share.yml
#

- name: check for entry in fstab
  mount:
    src:  '{{ mount_src }}'
    path: '{{ mount_dest }}'
    opts: 'username={{ mount_username }},password={{ mount_password}},domain={{ mount_share_domain }},uid={{ mount_uid }},gid={{ mount_gid }}'
    fstype: 'cifs'
    state: 'present'
  no_log: true
  become: true
  register: mount_status

- name: mount
  mount:
    src:  '{{ mount_src }}'
    path: '{{ mount_dest }}'
    opts: 'username={{ mount_username }},password={{ mount_password}},domain={{ mount_share_domain }},uid={{ mount_uid }},gid={{ mount_gid }}'
    fstype: 'cifs'
    state: 'mounted'
  no_log: true
  become: true
