- name: change hostname
  include_role:
    name: common
    tasks_from: change_hostname.yml

- name: change ansible user password
  user:
    name: ansible
    update_password: always
    password: "{{ all_ansible_password | password_hash('sha512') }}"
  become: true

- name: disable root password
  user:
    name: root
    password: '!'
  become: true

- name: set timezone
  timezone:
    name: '{{ all_system_timezone }}'
  become: true

- name: update packages
  apt:
    name: "*"
    state: latest
    force_apt_get: true
  become: true