---
#
# roles/common/snapshot.yml
#

- name: import vCenter credentials
  include_vars:
    file: '{{ item }}'
  with_items:
    - main.yml
    - vault.yml
  no_log: true
  
- name: get vm facts
  local_action:
    module: vmware_vm_facts
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_validate }}'
  register: vmfacts

- name: create snapshot
  local_action:
    module: vmware_guest_snapshot
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_datacenter }}'
    validate_certs: '{{ vcenter_validate }}'
    folder: /vm
    name: '{{ inventory_hostname }}'
    uuid: "{{ vmfacts['virtual_machines'][inventory_hostname]['uuid']  }}"
    state: present
    snapshot_name: '{{ snapshot_name }}'
    description: 'Created by Ansible: {{ snapshot_details }}'
    memory_dump: yes