---
#
# roles/common/tasks/update_packages.yml
#

- name: upgrade apt packages manually 
  shell: 'apt-get update'
  args:
    warn: no
  changed_when: false
  become: true

- name: copy dpkg lock script
  copy:
    src: 'check_lock.sh'
    dest: '/usr/local/bin/check_lock.sh'
    mode: 'a+x'
  become: true

- name: wait for dpkg lock to release
  shell: '/usr/local/bin/check_lock.sh'
  changed_when: false

- name: install packages
  apt: 
    state: latest
    update_cache: no
  become: true
