---
#
#Let's Encrypt support for staging CA
#

- name: install pip 
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: clone dehydrated repo
  git:
    repo: '{{ dehydrated_repo }}'
    dest: '{{ dehydrated_dest }}'

- name: install godaddypy python module
  pip:
    name: godaddypy  
    state: latest

- name: create godaddy api key file
  ini_file:
    path: '{{ dehydrated_dest }}/.gdkeys'
    owner: '{{ web_user }}'
    group: '{{ web_user }}'
    mode: 0600
    section: API
    option: '{{ item.o }}'
    value: '{{ item.v }}'
  with_items:
    - {o: 'key', v: '{{ godaddy_key }}'}
    - {o: 'secret', v: '{{ godaddy_secret }}'} 

- name: create domain list
  lineinfile:
    state: present
    create: yes
    path: '{{ dehydrated_dest }}/domains'
    line: '{{ item }}'
  with_items: '{{ domains }}'

- name: copy godaddy dns hook script
  copy:
    src: godaddy.py
    dest: '{{ dehydrated_dest }}'
    owner: '{{ web_user }}'
    group: '{{ web_user }}'
    mode: 0755

- name: copy dehydrated config files
  template:
    src: '{{ item }}'
    dest: '{{ dehydrated_dest }}'
    owner: '{{ web_user }}'
    group: '{{ web_user }}'
    mode: 0644
  with_items:
    - 'config.prod'
    - 'config.staging'

- name: enable staging Let's Encrypt CA
  file:
    state: link
    src: '{{ dehydrated_dest }}/config.staging'
    dest: '{{ dehydrated_dest }}/config'

- name: setup cron job
  cron:
    name: Let's Encrypt daily certificate check
    special_time: daily
    job: '{{ dehydrated_dest }}/dehydrated --cron --accept-terms --config {{ dehydrated_dest }}/config --hook {{ dehydrated_dest }}/godaddy.py'

- name: generate initial certificates
  shell: '{{ dehydrated_dest }}/dehydrated --cron --accept-terms --config {{ dehydrated_dest }}/config --hook {{ dehydrated_dest }}/godaddy.py' 